# Generated by Django 5.0.13 on 2025-03-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_pagevisit_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='subdomain',
        ),
    ]
